version: "3.7"
services:
  app:
    build:
      args:
        user: dev
        uid: 1000
      context: ./
      dockerfile: dockers/Dockerfile
    image: custom
    container_name: custom_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./dockers/php:/usr/local/etc/php/conf.d/php.ini
    networks:
      - custom_net

  db:
    image: mysql:5.7
    container_name: custom_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dockers/mysql:/etc/mysql/conf.d
    ports:
      - 3308:3306
    networks:
      - custom_net

  nginx:
    image: nginx:alpine
    container_name: custom_nginx
    restart: unless-stopped
    ports:
      - 8004:80
    links:
      - app
      - db
    volumes:
      - ./:/var/www
      - ./dockers/nginx:/etc/nginx/conf.d/
    networks:
      - custom_net

networks:
  custom_net:
    driver: bridge
